package mysql.src.ast;

public enum IRType {
    kProgram, kStmtlist, kStmt, kCreateStmt, kDropStmt, kAlterStmt, kSelectStmt,
    kSelectWithParens, kSelectNoParens, kSelectClauseList, kSelectClause,
    kCombineClause, kOptFromClause, kSelectTarget, kOptWindowClause,
    kWindowClause, kWindowDefList, kWindowDef, kWindowName, kWindow,
    kOptPartition, kOptFrameClause, kRangeOrRows, kFrameBoundStart,
    kFrameBoundEnd, kFrameBound, kOptExistWindowName, kOptGroupClause,
    kOptHavingClause, kOptWhereClause, kWhereClause, kFromClause, kTableRef,
    kOptIndex, kOptOn, kOptUsing, kColumnNameList, kOptTablePrefix, kJoinOp,
    kOptJoinType, kExprList, kOptLimitClause, kLimitClause, kOptLimitRowCount,
    kOptOrderClause, kOptOrderNulls, kOrderItemList, kOrderItem,
    kOptOrderBehavior, kOptWithClause, kCteTableList, kCteTable, kCteTableName,
    kOptAllOrDistinct, kCreateTableStmt, kCreateIndexStmt, kCreateTriggerStmt,
    kCreateViewStmt, kOptTableOptionList, kTableOptionList, kTableOption,
    kOptOpComma, kOptIgnoreOrReplace, kOptViewAlgorithm, kOptSqlSecurity,
    kOptIndexOption, kOptExtraOption, kIndexAlgorithmOption, kLockOption,
    kOptOpEqual, kTriggerEvents, kTriggerName, kTriggerActionTime,
    kDropIndexStmt, kDropTableStmt, kOptRestrictOrCascade, kDropTriggerStmt,
    kDropViewStmt, kInsertStmt, kInsertRest, kSuperValuesList, kValuesList,
    kOptOnConflict, kOptConflictExpr, kIndexedColumnList, kIndexedColumn,
    kUpdateStmt, kAlterAction, kAlterConstantAction, kColumnDefList, kColumnDef,
    kOptColumnConstraintList, kColumnConstraintList, kColumnConstraint,
    kOptReferenceClause, kOptCheck, kConstraintType, kReferenceClause,
    kOptForeignKey, kOptForeignKeyActions, kForeignKeyActions, kKeyActions,
    kOptConstraintAttributeSpec, kOptInitialTime, kConstraintName, kOptTemp,
    kOptCheckOption, kOptColumnNameListP, kSetClauseList, kSetClause,
    kOptAsAlias, kExpr, kOperand, kCastExpr, kScalarExpr, kUnaryExpr,
    kBinaryExpr, kLogicExpr, kInExpr, kCaseExpr, kBetweenExpr, kExistsExpr,
    kFunctionExpr, kOptDistinct, kOptFilterClause, kOptOverClause, kCaseList,
    kCaseClause, kCompExpr, kExtractExpr, kDatetimeField, kArrayExpr,
    kArrayIndex, kLiteral, kStringLiteral, kBoolLiteral, kNumLiteral,
    kIntLiteral, kFloatLiteral, kOptColumn, kTriggerBody, kOptIfNotExist,
    kOptIfExist, kIdentifier, kAsAlias, kTableName, kColumnName,
    kOptIndexKeyword, kViewName, kFunctionName, kBinaryOp, kOptNot, kName,
    kTypeName, kCharacterType, kCharacterWithLength, kCharacterWithoutLength,
    kCharacterConflicta, kNumericType, kOptTableConstraintList,
    kTableConstraintList, kTableConstraint, kOptEnforced, kUnknown,
}
